<?php
require_once '../../api/config.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'coach') {
    header('Location: ../../index.php');
    exit;
}

$coach_name = $_SESSION['name'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Calendar - Kasama Support Hub</title>
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="stylesheet" href="../../css/shared-styles.css">
    <link rel="stylesheet" href="../../css/coach-calendar-styles.css">
    <link rel="stylesheet" href="../../css/dark-mode.css">
    <script src="../../js/dark-mode.js"></script>
</head>
<body>
    <nav class="top-nav">
        <div class="nav-content">
            <div class="nav-left"><span class="nav-title">Kasama Support Hub</span></div>
            <div class="nav-right">
                <a href="../../api/logout.php" style="color:white; text-decoration:none; font-weight:bold; font-size:13px;">Logout</a>
            </div>
        </div>
    </nav>

    <div class="dashboard-wrapper">
        <header class="dashboard-header">
            <div class="header-left">
                <img src="../../images/phinma-logo.png" alt="Logo" class="header-logo" style="width:36px; height:36px;">
                <span class="header-title" style="font-size:15px; font-weight:600;">Calendar Management</span>
            </div>
            <div class="header-right">
                <button class="btn-secondary" onclick="window.location.href='dashboard.php'">← Back</button>
                <button class="btn-secondary" onclick="window.location.href='appointments.php'">📋 Appointments</button>
            </div>
        </header>

        <main class="calendar-container">
            <div class="page-header">
                <h1>📅 Manage Your Calendar</h1>
            </div>
            
            <!-- Legend -->
            <div class="legend">
                <div class="legend-item">
                    <div class="legend-dot available"></div>
                    <span>Available</span>
                </div>
                <div class="legend-item">
                    <div class="legend-dot blocked"></div>
                    <span>Blocked</span>
                </div>
                <div class="legend-item">
                    <div class="legend-dot booked"></div>
                    <span>Booked</span>
                </div>
            </div>
            
            <!-- Calendar Navigation -->
            <div class="calendar-nav">
                <button class="nav-btn" onclick="previousMonth()">← Prev</button>
                <span class="month-display" id="monthDisplay">January 2026</span>
                <button class="nav-btn" onclick="nextMonth()">Next →</button>
                <button class="nav-btn" onclick="goToToday()">Today</button>
            </div>
            
            <!-- Calendar Grid -->
            <div class="calendar-grid" id="calendarGrid">
                <!-- Generated by JavaScript -->
            </div>
        </main>
    </div>

    <!-- Slot Modal -->
    <div id="slotModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="slotModalTitle">Manage Time Slot</h3>
                <button class="modal-close" onclick="closeModal()">&times;</button>
            </div>
            <div id="slotModalContent">
                <div class="form-group">
                    <label>📅 Date</label>
                    <input type="text" id="slotDate" readonly>
                </div>
                <div class="form-group">
                    <label>🕐 Time</label>
                    <input type="text" id="slotTime" readonly>
                </div>
                <div class="form-group">
                    <label>📝 Notes (optional)</label>
                    <textarea id="slotNotes" placeholder="e.g., Meeting, Training, Leave..."></textarea>
                </div>
                <div class="form-actions">
                    <button class="btn-secondary" onclick="closeModal()">Cancel</button>
                    <button class="btn-primary" id="slotActionBtn" style="background:#c62828;" onclick="toggleSlotBlock()">🚫 Block Slot</button>
                </div>
            </div>
        </div>
    </div>

    <script>
    let currentMonth = <?php echo date('n') - 1; ?>;
    let currentYear = <?php echo date('Y'); ?>;
    let availabilityData = {};
    let bookingsData = {};
    const timeSlots = ['8:00 AM', '9:30 AM', '11:00 AM', '1:30 PM', '3:00 PM', '4:30 PM'];
    
    let selectedDate = '';
    let selectedTime = '';
    let selectedStatus = '';
    
    // Month names
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 
                        'July', 'August', 'September', 'October', 'November', 'December'];
    
    // Initialize
    document.addEventListener('DOMContentLoaded', () => {
        loadAvailability();
    });
    
    // Load availability data from server
    async function loadAvailability() {
        const startDate = new Date(currentYear, currentMonth, 1);
        const endDate = new Date(currentYear, currentMonth + 1, 0);
        
        const start = startDate.toISOString().split('T')[0];
        const end = endDate.toISOString().split('T')[0];
        
        try {
            const response = await fetch(`../../api/manage-availability.php?action=get&start=${start}&end=${end}`);
            const result = await response.json();
            
            if (result.success) {
                availabilityData = result.availability || {};
                bookingsData = result.bookings || {};
            }
        } catch (e) {
            console.error('Failed to load availability:', e);
        }
        
        generateCalendar();
    }
    
    // Generate calendar
    function generateCalendar() {
        const grid = document.getElementById('calendarGrid');
        document.getElementById('monthDisplay').textContent = monthNames[currentMonth] + ' ' + currentYear;
        
        // Headers
        let html = `
            <div class="calendar-header-cell">Sun</div>
            <div class="calendar-header-cell">Mon</div>
            <div class="calendar-header-cell">Tue</div>
            <div class="calendar-header-cell">Wed</div>
            <div class="calendar-header-cell">Thu</div>
            <div class="calendar-header-cell">Fri</div>
            <div class="calendar-header-cell">Sat</div>
        `;
        
        const firstDay = new Date(currentYear, currentMonth, 1).getDay();
        const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
        const today = new Date();
        today.setHours(0,0,0,0);
        
        // Empty cells
        for (let i = 0; i < firstDay; i++) {
            html += '<div class="calendar-cell other-month"></div>';
        }
        
        // Days
        for (let day = 1; day <= daysInMonth; day++) {
            const dateObj = new Date(currentYear, currentMonth, day);
            const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const isToday = dateObj.getTime() === today.getTime();
            const isPast = dateObj < today;
            const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;
            
            let cellClasses = ['calendar-cell'];
            if (isToday) cellClasses.push('today');
            if (isWeekend) cellClasses.push('weekend');
            
            // Count blocked slots
            const dayAvailability = availabilityData[dateStr] || {};
            const dayBookings = bookingsData[dateStr] || {};
            let blockedCount = Object.values(dayAvailability).filter(v => v.status === 'blocked').length;
            if (blockedCount > 0) cellClasses.push('has-blocked');
            
            html += `<div class="${cellClasses.join(' ')}" data-date="${dateStr}">`;
            html += `<div class="day-number ${isToday ? 'today' : ''}">${day}</div>`;
            
            // Time slots (only for non-weekend, non-past)
            if (!isWeekend && !isPast) {
                timeSlots.forEach(slot => {
                    const slotStatus = dayAvailability[slot]?.status || 'available';
                    const booking = dayBookings[slot];
                    
                    let slotClass = 'time-slot-mini';
                    let slotText = slot;
                    
                    if (booking) {
                        slotClass += ' booked';
                        slotText = `${slot} - ${booking.student_name.split(' ')[0]}`;
                    } else if (slotStatus === 'blocked') {
                        slotClass += ' blocked';
                    } else {
                        slotClass += ' available';
                    }
                    
                    html += `<div class="${slotClass}" onclick="openSlotModal('${dateStr}', '${slot}', '${slotStatus}', ${booking ? 'true' : 'false'})">${slotText}</div>`;
                });
                
                // Day action buttons
                if (blockedCount === timeSlots.length) {
                    html += `<div class="day-actions"><button class="btn-unblock-day" onclick="unblockDay('${dateStr}')">Unblock Day</button></div>`;
                } else if (blockedCount === 0 && Object.keys(dayBookings).length === 0) {
                    html += `<div class="day-actions"><button class="btn-block-day" onclick="blockDay('${dateStr}')">Block Day</button></div>`;
                }
            } else if (isWeekend) {
                html += '<div class="cell-label">Weekend</div>';
            } else if (isPast) {
                html += '<div class="cell-label">Past</div>';
            }
            
            html += '</div>';
        }
        
        grid.innerHTML = html;
    }
    
    // Navigation
    function previousMonth() {
        currentMonth--;
        if (currentMonth < 0) { currentMonth = 11; currentYear--; }
        loadAvailability();
    }
    
    function nextMonth() {
        currentMonth++;
        if (currentMonth > 11) { currentMonth = 0; currentYear++; }
        loadAvailability();
    }
    
    function goToToday() {
        currentMonth = new Date().getMonth();
        currentYear = new Date().getFullYear();
        loadAvailability();
    }
    
    // Modal functions
    function openSlotModal(date, time, status, isBooked) {
        if (isBooked) {
            alert('This slot has an active booking. Manage it from the Appointments page.');
            return;
        }
        
        selectedDate = date;
        selectedTime = time;
        selectedStatus = status;
        
        document.getElementById('slotDate').value = date;
        document.getElementById('slotTime').value = time;
        document.getElementById('slotNotes').value = '';
        
        const btn = document.getElementById('slotActionBtn');
        if (status === 'blocked') {
            btn.textContent = '✅ Unblock Slot';
            btn.style.background = '#4a7c2c';
        } else {
            btn.textContent = '🚫 Block Slot';
            btn.style.background = '#c62828';
        }
        
        document.getElementById('slotModal').style.display = 'block';
    }
    
    function closeModal() {
        document.getElementById('slotModal').style.display = 'none';
    }
    
    async function toggleSlotBlock() {
        const newStatus = selectedStatus === 'blocked' ? 'available' : 'blocked';
        const notes = document.getElementById('slotNotes').value;
        
        const formData = new FormData();
        formData.append('action', 'block');
        formData.append('date', selectedDate);
        formData.append('time_slot', selectedTime);
        formData.append('status', newStatus);
        formData.append('notes', notes);
        
        try {
            const response = await fetch('../../api/manage-availability.php', { method: 'POST', body: formData });
            const result = await response.json();
            
            if (result.success) {
                closeModal();
                loadAvailability();
            } else {
                alert('Error: ' + result.message);
            }
        } catch (e) {
            alert('Connection error');
        }
    }
    
    async function blockDay(date) {
        if (!confirm('Block all time slots for ' + date + '?')) return;
        
        const formData = new FormData();
        formData.append('action', 'block_day');
        formData.append('date', date);
        formData.append('notes', 'Day blocked');
        
        try {
            const response = await fetch('../../api/manage-availability.php', { method: 'POST', body: formData });
            const result = await response.json();
            
            if (result.success) {
                loadAvailability();
            } else {
                alert('Error: ' + result.message);
            }
        } catch (e) {
            alert('Connection error');
        }
    }
    
    async function unblockDay(date) {
        if (!confirm('Unblock all time slots for ' + date + '?')) return;
        
        const formData = new FormData();
        formData.append('action', 'unblock_day');
        formData.append('date', date);
        
        try {
            const response = await fetch('../../api/manage-availability.php', { method: 'POST', body: formData });
            const result = await response.json();
            
            if (result.success) {
                loadAvailability();
            } else {
                alert('Error: ' + result.message);
            }
        } catch (e) {
            alert('Connection error');
        }
    }
    
    // Close modal on outside click
    window.onclick = function(e) {
        if (e.target.classList.contains('modal')) {
            e.target.style.display = 'none';
        }
    }
    </script>
</body>
</html>